# Site settings
title: TeamRGE
description: |
  The industry experts with focus on remoting graphics, and GPUs for virtual desktops and applications.
owner: TeamRGE # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: team@teamrge.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.teamrge.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/TeamRGE
  email: 'mailto:team@teamrge.com?subject=TeamRGE: Contact'
  youtube-square: https://www.youtube.com/channel/UCzsbidFeFG1K2tG7x72vtvQ

# Members
members:
  ruben:
    name: Ruben
    display_name: Ruben Spruijt
    company: Dizzion
    title: Field CTO
    picture: assets/images/members/ruben.png
    page: ruben-spruijt
    social:
      twitter: https://twitter.com/rspruijt
      linkedin: https://www.linkedin.com/in/rspruijt
      email: ruben@rspruijt.com
  shawn:
    name: Shawn
    display_name: Shawn Bass
    company: VMware
    title: start-up advisor and former EUC CTO of Desktop Technologies
    picture: assets/images/members/shawn.png
    page: shawn-bass
    social:
      twitter: https://twitter.com/shawnbass
      linkedin: https://www.linkedin.com/in/shawnbass/
      email: shawn@shawnbass.com
  benny:
    name: Benny
    display_name: Dr. Benny Tritsch
    company: ControlUp
    title: Technical Evangelist
    picture: assets/images/members/benny.png
    page: benny-tritsch
    social:
      twitter: https://twitter.com/drtritsch
      linkedin: https://www.linkedin.com/in/drtritsch/
  ryan:
    name: Ryan
    display_name: Ryan Ververs-Bijkerk
    company: GO-INIT
    title: Technical Evangelist
    picture: assets/images/members/ryan.png
    page: ryan-ververs-bijkerk
    social:
      twitter: https://twitter.com/logitblog
      linkedin: https://www.linkedin.com/in/ryanbijkerk
      github: https://github.com/RyanBijkerk
      reddit: https://www.reddit.com/u/ryanbijkerk
      web1: https://www.logitblog.com
      web2: https://www.go-euc.com
  bram:
    name: Bram
    display_name: Bram Wolfs
    company: Wolfs IT Solutions
    title: Consultant
    picture: assets/images/members/bram.png
    page: bram-wolfs
    social:
      linkedin: https://www.linkedin.com/in/bramwolfs/
      twitter: https://twitter.com/bramwolfs
  magnar:
    name: Magnar
    display_name: Magnar Johnson
    company: Firstpoint Bergen
    title: Owner
    picture: assets/images/members/magnar.png
    page: magnar-johnson
  thomas:
    name: Thomas
    display_name: Thomas Poppelgaard
    company: Poppelgaard.com
    title: Independent Consultant and Technology Evangelist
    picture: assets/images/members/thomas.png
    page: thomas-poppelgaard
    social:
      twitter: https://twitter.com/_POPPELGAARD
      linkedin: https://www.linkedin.com/in/thomaspoppelgaard/
  patrick:
    name: Patrick
    display_name: Patrick van den Born
    company: van den Born IT Consultancy
    title: Freelance Senior IT Consultant & IT Architect
    picture: assets/images/members/patrick.png
    page: patrick-van-den-born
    social:
      twitter: https://twitter.com/pvdnborn
      linkedin: https://www.linkedin.com/in/patrick-van-den-born-2b3567a/
  rody:
    name: Rody
    display_name: Rody Kossen
    company: Citrix
    title: Senior Principal Quality Engineer
    picture: assets/images/members/rody.png
    page: rody-kossen
    social:
      twitter: https://twitter.com/R_Kossen
      linkedin: https://www.linkedin.com/in/rody-kossen-186b4b40/
  johan:
    name: Johan
    display_name: Johan van Amersfoort
    company: ITQ
    title: Technologist EUC & AI
    picture: assets/images/members/johan.png
    page: johan-van-amersfoort
    social:
      twitter: https://twitter.com/vhojan
      linkedin: https://www.linkedin.com/in/hojan/
  esther:
    name: Esther
    display_name: Esther Barthel
    company: Cognition IT
    title: Solutions Architect
    picture: assets/images/members/esther.png
    page: esther-barthel
    social:
      twitter: https://twitter.com/virtuEs_IT
      linkedin: https://www.linkedin.com/in/ebarthel/
  eltjo:
    name: Eltjo
    display_name: Eltjo van Gulik
    company: Citrix
    title: Principal Product Manager for HDX Graphics & Seamless
    picture: assets/images/members/eltjo.png
    page: eltjo-van-gulik
    social:
      twitter: https://twitter.com/eltjovg
      linkedin: https://www.linkedin.com/in/eltjovangulik/
      web: https://www.go-euc.com
  joe:
    name: Joe
    display_name: Joe DaSilva
    company: AMD
    title: PMTS, Solutions Architect, Cloud Graphics
    picture: assets/images/members/joe.png
    page: joe-dasilva
    social:
      linkedin: https://www.linkedin.com/in/joe-dasilva-p-eng-a8963418/
# Videos:
videos:
  xorivb_SSDI:
    title: 'TeamRGE 2020 - 12 NVIDIA Virtual Reality and EUC'
    description: 'By Thomas Poppelgaard. NVIDIA Virtual Reality in EUC environments.'
    url: teamrge-2020-12-nvidia-virtual-reality-and-euc
  FtKeGh-oPRc:
    title: 'TeamRGE 2020 - 11 HTML5 redirection in remote sessions'
    description: 'By Esther Barthel & GO-EUC. With Adobe stopping support for Flash by the end of the year and Citrix recommending to switch to HTML5 redirection, I was interested to test whether the HTML 5 Video redirection would save CPU resource consumption on the VDA. With the help of GO-EUC I was able to test the effect of HTML5 Redirection and now proudly present the preliminary results.'
    url: 'teamrge-2020-11-html5-redirection-in-remote-sessions'
  Xd0IZRcWiWo:
    title: 'TeamRGE 2020 - 10 RDP performance in GPU accelerated WVD sessions'
    description: 'By Benny Tritsch and Kristin Griffin. Over the last months, Benny and Kristin conducted several GPU-focused remote end-user experience benchmarking tests in Azure. Learn about the latest results and lessons learned.'
    url: 'teamrge-2020-10-rdp-performance-in-gpu-accelerated-wvd-sessions'
  vL5hIO_Je5M:
    title: 'TeamRGE 2020 - 09 GPU partitioning in Azure NVv4'
    description: 'By Joe DaSilva (AMD). A quick peek under the hood of GPU partitioning as used in Microsoft’s Azure NVv4 instances based on AMD’s MxGPU technology.'
    url: 'teamrge-2020-09-gpu-partitioning-in-azure-nvv4'
  sDvepW1x964:
    title: 'TeamRGE 2020 - 08 Update on NVIDIA GPUs for EUC'
    description: 'By Jits Langedijk (NVIDIA). Get up to speed with NVIDIA Virtual GPU. In this session you get to learn what NVIDIA has to offer for End User Computing solutions, for (mobile) workstations, datacenter, virtualization and cloud. Learn which GPU is best suited for your use case and if licensing applies to the use case.'
    url: 'teamrge-2020-08-update-on-nvidia-gpus-for-euc'
  G8F4xInxD18:
    title: 'TeamRGE 2020 - 07 NVIDIA and AMD GPUs in Azure WVD'
    description: 'By Thomas Poppelgaard. NVIDIA and AMD GPUs in Azure WVD'
    url: 'teamrge-2020-07-nvidia-and-amd-gpus-in-azure-wvd'
  KfjZNasLIKU:
    title: 'TeamRGE 2020 - 06 Remote graphic workloads and clients'
    description: 'By Rody Kossen & Patrick van den Born. As we add advanced GPUs to our virtual desktop environments, delivering the best user experience requires tweaking of remote display protocol settings like quality, compression, chroma subsampling, not to mention vendor-specific settings. But what about the different clients? In this intermediate-level session Rody Kossen and Patrick van den Born will show you the difference in user experience between clients and workloads. For the 2020 edition we’ve updated the session with the latest Citrix Virtual Apps and Desktops, VMware Horizon and Xi Frame protocols. You can also expect details about Windows Virtual Desktop and clients.'
    url: 'teamrge-2020-06-remote-graphic-workloads-and-clients'
  FbEooETsdc0:
    title: 'TeamRGE 2020 - 05 The real race against round trip time'
    description: 'By Ryan Ververs-Bijkerk. This will be the race of the year on the legendary Dutch race track, Zandvoort. The race is against our worst enemy, round trip time. This session will show and explain the negative effect of round trip time when delivering remote graphics intense applications from the public cloud.'
    url: 'teamrge-2020-05-the-real-race-against-round-trip-time'
  w4xVBCuZOZA:
    title: 'TeamRGE 2020 - 04 Connection Experience Indicator for RDS and WVD'
    description: 'By Bram Wolfs. In this session Bram shows you what the Connection Experience Indicator is and how you can configure and use it.'
    url: 'teamrge-2020-04-connection-experience-indicator-for-rds-and-wvd'
  r8Ob1_mn6WA:
    title: 'TeamRGE 2020 - 03 Why GPUs matter in EUC environments'
    description: 'By Benny Tritsch & Rody Kossen. In this geeky session Benny and Rody will show real-world examples of what the benefits of GPUs are in remoting environments.'
    url: 'teamrge-2020-03-why-gpus-matter-in-euc-environments'
  MaBJZ-dT9Yo:
    title: 'TeamRGE 2020 - 02 How Azure, AWS and GCP impact VDI and DaaS'
    description: 'By Ruben Spruijt. What does it really mean from a performance perspective to host traditional Windows applications and desktops in the cloud? You will learn why and how Azure, AWS and GCP deliver different storage performance and GPU options for VDI and DaaS. This unique information is key for solution design, sizing and managing VDI/DaaS performance expectations.'
    url: 'teamrge-2020-02-how-azure-aws-and-gcp-impact-vdi-and-daas'
  NZcJoMNSwdg:
    title: 'TeamRGE 2020 - 01 Opening Keynote'
    description: 'By Ruben Spruijt & Benny Tritsch. In this session, Benny and Ruben kick off the TeamRGE 2020 virtual event with a rundown of the most important driving factors in delivering a good remote user experience today. They also share some results of the latest VDI Like a Pro survey.'
    url: 'teamrge-2020-01-opening-keynote'

# Build settings
markdown: kramdown
permalink: /:title/
#sass:
#  style: compressed

plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext